name: datascrap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^1.2.1
  get: ^4.6.1
  intl: ^0.19.0
  page_transition: ^2.0.5
  syncfusion_flutter_datagrid: ^25.1.42
  tuple: ^2.0.0
  carousel_slider: ^4.0.0
  animated_splash_screen: ^1.2.0
  video_player:
  skeletons: ^0.0.3
  cached_network_image: ^3.2.0
  flutter_staggered_animations: ^1.0.0
  csv: ^6.0.0
  external_path: ^1.0.3
  grouped_list: ^5.1.2
  flip_card: ^0.7.0
  flutter_local_notifications: ^17.1.1
  provider: ^6.0.5
  lottie: ^3.1.0
  shared_preferences: ^2.0.18
  rxdart: any
  timezone: any
  image: ^4.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logos/
    - fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: RestaurantMenu
      fonts:
        - asset: fonts/RestaurantMenuHollow.ttf
    - family: Cocosharp
      fonts:
        - asset: fonts/Cocosharp.ttf
    - family: AmericanCaptain
      fonts:
        - asset: fonts/AmericanCaptain.ttf   
    - family: NewAthletic
      fonts:
        - asset: fonts/NewAthletic.ttf
    - family: Litsans
      fonts:
        - asset: fonts/Litsans.otf
    - family: Exo
      fonts:
        - asset: fonts/Exo/exo-2-0.black.otf
        - asset: fonts/Exo/exo-2-0.bold.otf
        - asset: fonts/Exo/exo-2-0.extra-bold.otf
        - asset: fonts/Exo/exo-2-0.extra-light.otf
        - asset: fonts/Exo/exo-2-0.light.otf
        - asset: fonts/Exo/exo-2-0.medium.otf
        - asset: fonts/Exo/exo-2-0.regular.otf
        - asset: fonts/Exo/exo-2-0.semi-bold.otf
        - asset: fonts/Exo/exo-2-0.thin.otf
    - family: Kanit
      fonts:
        - asset: fonts/Kanit/kanit.black.ttf
        - asset: fonts/Kanit/kanit.bold.ttf
        - asset: fonts/Kanit/kanit.extrabold.ttf
        - asset: fonts/Kanit/kanit.extralight.ttf
        - asset: fonts/Kanit/kanit.italic.ttf
        - asset: fonts/Kanit/kanit.light.ttf
        - asset: fonts/Kanit/kanit.medium.ttf
        - asset: fonts/Kanit/kanit.regular.ttf
        - asset: fonts/Kanit/kanit.semibold.ttf
        - asset: fonts/Kanit/kanit.thin.ttf    
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
